name: Dockerfile Vulnerability Scanning

on:
  push:
    branches:
      - "**"  # Trigger on all branches

jobs:
  scan-dockerfiles:
    runs-on: ubuntu-latest1234

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Trigger Vulnerability Check
      id: vulnerability_check
      run: |
        # Prepare request payload
        REPO_NAME="${{ github.repository }}"
        CLONE_URL="https://github.com/${REPO_NAME}.git"

        RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -d "$(jq -n --arg repo_name "$REPO_NAME" --arg clone_url "$CLONE_URL" \
              '{repository: {clone_url: $clone_url, name: $repo_name}}')" \
          http://<your-server-ip>:5000/webhook)

        # Handle response
        if [[ "$RESPONSE" -ne 200 ]]; then
          echo "Scan failed. Vulnerabilities detected:"
          cat response.json
          exit 1
        fi

    - name: Display Results
      if: always()
      run: |
        echo "Scan Results:"
        cat response.json
